project:
  type: book
  output-dir: docs
#include-in-header: custom-head.html

book:
  title: "Competing in the Age of AI"
  author: "Pamela Schlosser"
  date: "10/13/2025"
  chapters:
    - index.qmd
    - rethinkingfirm.qmd
    - genAI.qmd
    - ethics.qmd
    - dataAcquisition.qmd
    - webscrapingandapi.qmd
#    - callbacksandapis.qmd
    - storytelling.qmd
    - analyticsproblem.qmd
    - preparingpeople.qmd
    - introdash.qmd
    - crashcourse.qmd
    - github.qmd
#    - understandinghtml.qmd
    - makingcallbacks.qmd
    - multilayout.qmd
    - multipages.qmd
    - summary.qmd
    - references.qmd


format:
  html:
    css: styles.css
    number-sections: false
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"

editor: visual



